### ISSUE TITLE
Visual Studio 2017 RC support

### ISSUE THREAD

**Issue by MoamenMohamed** [JosefPihrt/SnippetEssentials#1]
Any news

**Comment by josefpihrt** [comment]
Hi, I encourage you to use my new extension [Snippetica](https://marketplace.visualstudio.com/items?itemName=josefpihrt.Snippetica). It offers snippets for multiple languages including [C#](https://github.com/JosefPihrt/Snippetica/blob/master/source/Snippetica.VisualStudio/Snippetica.CSharp/README.md) and the set of snippets is very similar to Snippet Essentials. Thanks.

**Comment by MoamenMohamed** [comment]
You are a lifesaver, Thank you.
