### ISSUE TITLE
Visual Studio 2017 support

### ISSUE THREAD

**Issue by koljada** [JosefPihrt/SnippetEssentials#2]
It would be great to make it working on Visual Studio 2017

**Comment by josefpihrt** [comment]
Thanks for using Snippet Essentials.

Snippet Essentials has evolved into Snippetica. It supports more languages and it has better documentation.

**Snippetica is virtually the next version of Snippet Essentials.**

[Snippetica on GitHub](https://github.com/JosefPihrt/Snippetica)
[Snippetica Extension for Visual Studio](https://marketplace.visualstudio.com/items?itemName=josefpihrt.Snippetica)

I hope you'll like it.

**Comment by koljada** [comment]
Thanks. Snippetica is also a great tool!
One remark: I think it would be great to have some simple site with filters. Similar to [this](http://pihrt.net/SnippetEssentials/SnippetList).

**Comment by josefpihrt** [comment]
@koljada There you go http://pihrt.net/Snippetica/Snippets

**Comment by koljada** [comment]
Cool! Thanks a lot
